apps/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'

urlpatterns = [
    path('index/', views.index_cms, name='index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('category_news/', views.category_news, name='category_news'),
    path('add_category/', views.add_category, name='add_category'),
    path('edit_category/', views.edit_category, name='edit_category'),
    path('del_category/', views.del_category, name='del_category'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('news_manage/', views.NewsManage.as_view(), name='news_manage'),
    path('edit_news/', views.EditNewsView.as_view(), name='edit_news'),
    path('del_news/', views.del_news, name='del_news'),
    path('staff_manage/', views.StaffView.as_view(), name='staff_manage'),
    path('del_staff/', views.del_staff, name='del_staff'),
]

apps/news/urls.py
from . import views
from django.urls import path

app_name = 'news'

urlpatterns = [
    path('news_list/', views.news_list, name='news_list'),
    path('<int:news_id>/', views.news_detail, name='news_detail'),
    path('basketball_news/', views.basket_news_view, name='basketball_news'),
    path('autocar_news/', views.autocar_news_view, name='autocar_news'),
    path('comment/', views.comment_view, name='comment'),
]

mysite/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.news import views

urlpatterns = [
    path('',views.index_view, name='index'),
    path('news/', include('apps.news.urls')),
    path('auth/', include('apps.login.urls')),
    path('cms/', include('apps.cms.urls')),
    path('ueditor/', include('apps.ueditor.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# 添加MEDIA_ROOT下的访问路径

apps/cms/models.py
from django.db import models
from apps.login.models import User


class AddCategory(models.Model):
    name = models.CharField(max_length=100)


class News(models.Model):
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=200)
    thumbnail = models.URLField()
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    # 如果到时候分类删除，此新闻保留。
    category = models.ForeignKey(AddCategory, on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    # 在此声明排列顺序，那么所有数据都按这个规则排列
    class Meta:
        ordering = ['-pub_time']

apps/news/models.py
from django.db import models
from apps.login.models import User
from apps.cms.models import News


class Comment(models.Model):
    comment_content = models.TextField()  # 评论内容
    pub_time = models.DateTimeField(auto_now_add=True)  # 发布时间
    comment_author = models.ForeignKey(User, on_delete=models.CASCADE)  # 发布者
    comment_news = models.ForeignKey(News, on_delete=models.CASCADE, related_name='comments')  # 评论所属的新闻

apps/cms/forms.py
from django import forms
from apps.cms.models import News
from apps.forms import FormMixin


# 编辑新闻分类表单
class EditCategoryForm(forms.Form):
    pk = forms.IntegerField()
    name = forms.CharField(max_length=100)


#  创建一个表单类，来对新闻发布页面的数据进行提取，发布时间不需要，作者也不需要，分类也不需要(为了实验一下，暂时需要)
#  分类不需要是因为需要重新定义，要提取一个整型的数据
#  在此实验了分类这个字段要不要重新定义，结果是可以不需要重新定义
class WriteNewsForm(forms.ModelForm, FormMixin):
    # category = forms.IntegerField()

    class Meta:
        model = News
        # exclude = ['author', 'pub_time', 'category']
        exclude = ['author', 'pub_time']


# 编辑新闻表单
class EditNewsForm(forms.ModelForm, FormMixin):
    id = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['author', 'pub_time']

apps/cms/views.py
from django.contrib.auth.models import Group
from django.views.generic import View
from django.shortcuts import render, redirect, reverse
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.http import require_POST, require_GET
from apps.cms.models import AddCategory, News
from utils import restful
from .forms import EditCategoryForm, EditNewsForm
import os
from django.conf import settings
from .forms import WriteNewsForm
from datetime import datetime
from django.utils.timezone import make_aware
from apps.login.models import User
from apps.cms.decorator import blog_super_decorator
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required


# 如果不是公司员工，则不能进入下面的视图函数渲染的页面，CMS页面主页
@staff_member_required(login_url='index')
def index_cms(request):
    return render(request, 'cms/index.html')


# CMS发布新闻页面
# def write_news(request):
#     categories = AddCategory.objects.all()
#     context = {
#         'categories': categories
#     }
#     return render(request, 'cms/write_news.html', context=context)

# 将上面的代码改写，因为涉及到了新闻发布时需要POST请求，改为类视图
# 注意这个类视图的引用/from django.views.generic import View
# 类视图必须用method_decorator装饰器包裹起来，perm是权限的名称，login_url是没有权限要跳转的页面
@method_decorator(permission_required(perm='news.add_news', login_url='/'), name='dispatch')
class WriteNewsView(View):

    def get(self, request):
        categories = AddCategory.objects.all()
        context = {
            'categories': categories
        }
        return render(request, 'cms/write_news.html', context=context)

    # 接受发布新闻时用户输入的数据得使用POST方法，还要写一个models,映射数据库,写一个表单类，进行提取数据
    def post(self, request):
        form = WriteNewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category = form.cleaned_data.get('category')
            # category_id = form.cleaned_data.get('category')  # 这里实验了这两个方式，展示出来的结果是不是一样，结果是一样。
            # category = AddCategory.objects.get(pk=category_id)
            print(category)  # 实验上面两种代码，返回的结果都是一样的，都是AddCategory object (14)，即一个对象，还是需要前端代码中调用他的属性名
            # 所以依照代码越少的原则，使用只有一行代码的
            News.objects.create(title=title, desc=desc, thumbnail=thumbnail,
                                content=content, category=category, author=request.user)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())


@method_decorator(permission_required(perm='news.change_news', login_url='/'), name='dispatch')
class EditNewsView(View):

    # 实现get请求后，可以将需要修改的数据拿到，修改完也可以提交，但是是新增一个文章了。这不是想要的，只是需要修改。
    def get(self, request):
        news_id = request.GET.get('news_id')
        news = News.objects.get(id=news_id)
        # print(type(news))
        context = {
            'news': news,
            'categories': AddCategory.objects.all()
        }
        return render(request, 'cms/write_news.html', context=context)

    # 修改新闻的视图函数写完了，当点击提交按钮时，如何判断这个新闻是不是修改的呢？可以再按键上绑定新闻的ID，如果有这个ID，说明是要修改的
    def post(self, request):
        form = EditNewsForm(request.POST)
        # print(121213)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category = form.cleaned_data.get('category')
            pk = form.cleaned_data.get('id')
            News.objects.filter(id=pk).update(title=title, desc=desc, thumbnail=thumbnail, content=content,
                                              category=category)
            # print(121212)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())


@require_POST
@permission_required(perm='news.change_news', login_url='/')
def del_news(request):
    news_id = request.POST.get('pk')
    News.objects.filter(pk=news_id).delete()
    return restful.ok()


# 新闻发布页面中的新闻分类页面
@require_GET
@permission_required(perm='news.change_addcategory', login_url='/')
def category_news(request):
    context = {
        'categories': AddCategory.objects.all()
    }
    return render(request, 'cms/category.html', context=context)


# 新闻分类页面中，增加新闻分类
@require_POST
@permission_required(perm='news.add_addcategory', login_url='/')
def add_category(request):
    name = request.POST.get('name')
    exists = AddCategory.objects.filter(name=name)
    if not exists:
        AddCategory.objects.create(name=name)
        return restful.ok()
    else:
        return restful.params_error(message='分类已存在~')


# 新闻分类页面中，修改新闻分类
@require_POST
@permission_required(perm='news.change_addcategory', login_url='/')
def edit_category(request):
    form = EditCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data['pk']
        name = form.cleaned_data['name']
        exists = AddCategory.objects.filter(name=name)
        if not exists:
            try:
                AddCategory.objects.filter(pk=pk).update(name=name)
                return restful.ok()
            except:
                return restful.params_error(message='分类不存在')
        else:
            return restful.params_error(message='分类已存在~')
    return restful.params_error(message='重新操作！')


# 新闻分类页面中，删除新闻分类
@require_POST
@permission_required(perm='news.delete_addcategory', login_url='/')
def del_category(request):
    pk = request.POST.get('pk')
    try:
        categories = AddCategory.objects.filter(pk=pk).delete()
        return restful.ok()
    except:
        return restful.params_error(message='分类不存在')


# 下面写的是新闻发布页面中，点击上传文件的视图函数。
@require_POST
@permission_required(perm='news.add_news', login_url='/')
def upload_file(request):
    file = request.FILES.get('file')  # 此处的get中的file是你要获取的文件的字段名，要跟前端保持一致。
    name = file.name  # 然后获取文件的名字。
    with open(os.path.join(settings.MEDIA_ROOT, name), 'wb') as uf:  # 此处是打开文件，以2进制的方式写入
        for chunk in file.chunks():  # chunks()函数是 读取文件并生成'chunk_size'字节块，所以要将其遍历出来，可以查看源码
            uf.write(chunk)  # 将读取出来的字节写入uf中，其实也就是上传
    url = request.build_absolute_uri(settings.MEDIA_URL + name)
    return restful.result(data={'url': url})


# 新闻管理中的查询视图函数
@method_decorator(permission_required(perm='news.add_news', login_url='/'), name='dispatch')
class NewsManage(View):

    def get(self, request):
        # 这里get得到的是字符串，需要转换为整数
        start = request.GET.get('start')
        end = request.GET.get('end')
        title = request.GET.get('title')
        # request.GET.get(参数)
        # 这个默认值是只有 这个参数没有传递时,得到的是一个NoneType，会报错
        # 那么就设置一个0，当参数没有值时，用0代替
        category_id = int(request.GET.get('category') or 0)
        newses = News.objects.select_related('author', 'category')

        if start or end:
            if start:
                start_date = datetime.strptime(start, '%Y/%m/%d')  # 将字符串时间格式化
            else:
                start_date = datetime(year=2019, month=1, day=1)  # 如果用户没有选择开始时间，则设置为2019/1/1
            if end:
                end_date = datetime.strptime(end, '%Y/%m/%d')
            else:
                end_date = datetime.now()
            # start_date, end_date 都是幼稚时间，pub_time是清醒时间，所以下面代码会报错
            # from django.utils.timezone import make_aware 调用这个方法可以将幼稚时间转为清醒时间
            # newses = newses.filter(pub_time__range=(start_date, end_date))  # 从开始时间，结束时间之间过滤
            newses = newses.filter(pub_time__range=(make_aware(start_date), make_aware(end_date)))  # 从开始时间，结束时间之间过滤
        if title:
            newses = newses.filter(title__icontains=title)  # 不区分大小写 ，包含的意思
            # print(title)
        if category_id:
            newses = newses.filter(category=category_id)
            # print(category_id)
        context = {
            'newses': newses,
            'categories': AddCategory.objects.all(),
            'title': title,
            'start': start,
            'end': end,
            'category_id': category_id

        }
        return render(request, 'cms/newsmanage.html', context=context)


# 类视图函数不能直接调用装饰器，需要借助@method_decorator()方法，method_decorator的作用是为函数视图装饰器补充第一个self参数，以适配类视图方法
# 装饰器需要的第一个参数是 request对象, 但我们调用类视图中请求方法时, 传入的第一个参数不是request对象，而是self 视图对象本身，第二个位置参数才是request对象
# 所以如果直接将用于函数视图的装饰器装饰类视图方法，会导致参数传递出现问题。
# 这么dispatch不知道什么意思，为类视图函数下面的所有方法添加装饰器
# @method_decorator 中添加name属性，可以为特定的方法添加装饰器，比如get ,post某个特定的
# 装饰器一些使用方法不懂的看博客
@method_decorator(blog_super_decorator, name='dispatch')
class StaffView(View):

    def get(self, request):
        staffs = User.objects.filter(is_staff=True)
        groups = Group.objects.all()
        context = {
            "staffs": staffs,
            'groups': groups
        }
        return render(request, 'cms/staffs.html', context=context)

    def post(self, request):
        telephone = request.POST.get('telephone')
        user = User.objects.filter(telephone=telephone).first()
        print(user)
        if user:
            user.is_staff = True
            group_id = request.POST.get('group')
            group = Group.objects.filter(id=group_id).first()
            # print(group)
            user.groups.add(group)
            user.save()
            return restful.ok()
        else:
            return restful.params_error(message='这个员工好像不存在呀！~')


@require_POST
@blog_super_decorator
def del_staff(request):
    telephone = request.POST.get('telephone')
    print(telephone)
    try:
        staff = User.objects.filter(telephone=telephone).delete()
        return restful.ok()
    except:
        return restful.params_error(message='员工不存在！')

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bokebook | CMS后台管理中心</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/Ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/ajax.min.js' %}"></script>
    <script src="{% static 'js/alert.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    <link rel="shortcut icon" href="#"/>
    {% block head %}

    {% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <!-- 下面是CMS页面顶部代码 -->
    <header class="main-header">
        <!-- Logo -->
        <a href="" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>CMS</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>CMS</b>后台发布中心</span>
        </a>
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only"></span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">

                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="https://tse3-mm.cn.bing.net/th?id=OIP.1XeSHiOCQ6xdU9SdzkgAKQHaHd&w=197&h=198&c=7&o=5&dpr=1.25&pid=1.7"
                                 class="user-image" alt="User Image">
                            <span class="hidden-xs">火箭熊</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="https://tse3-mm.cn.bing.net/th?id=OIP.1XeSHiOCQ6xdU9SdzkgAKQHaHd&w=197&h=198&c=7&o=5&dpr=1.25&pid=1.7"
                                     class="img-circle" alt="User Image">

                                <p>
                                    <small>这里面装着介绍</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#" class="btn btn-default btn-flat">退出</a>
                                </div>
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>
        </nav>
    </header>
    <!-- CMS页面左侧可隐藏代码 -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar" style="height: auto;">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="https://tse3-mm.cn.bing.net/th?id=OIP.1XeSHiOCQ6xdU9SdzkgAKQHaHd&w=197&h=198&c=7&o=5&dpr=1.25&pid=1.7"
                         class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>火箭熊</p>
                    <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                </div>
            </div>

        </section>
        <ul class="sidebar-menu" data-widget="tree">
            <li class="active">
                <a href="{% url 'cms:index' %}"><i class="fa fa-home"></i><span>首页</span></a>
            </li>

            {# 下面对权限进行限定，如果有权限则可以看到并能操作，这个perms是settings中的auth上下文处理器返回的 #}
            {% if perms.news.change_news %}
                <li>
                    <a href="{% url 'cms:write_news' %}"><i class="fa fa-pencil-square-o"></i><span>发布新闻</span></a>
                </li>
                <li>
                    <a href="{% url 'cms:category_news' %}"><i class="fa fa-tag"></i><span>新闻分类</span></a>
                </li>
                <li>
                    <a href="{% url 'cms:news_manage' %}"><i class="fa fa-list"></i><span>新闻管理</span></a>
                </li>
            {% endif %}
            {% if perms.news.delete_comment %}
                {# 管理评论功能还为实现 留空待实现#}
            {% endif %}

            {% if user.is_superuser %}
                <li>
                    <a href="{% url 'cms:staff_manage' %}"><i class="fa fa-list"></i><span>员工管理</span></a>
                </li>
            {% endif %}
            <li>
                <a href="{% url 'index' %}" target="_blank"><i class="fa fa-home"></i><span>返回博客首页</span></a>
            </li>
        </ul>
    </aside>
    <!-- CMS主题部分代码 -->
    <div class="content-wrapper">
        <section class="content-header">
            {% block content-header %}

            {% endblock %}
        </section>
        <section class="content">
            {% block content %}{% endblock %}
        </section>
    </div>
    <!-- CMS主题部分底部代码-->
    <footer class="main-footer">
        <span>欢迎来到CMS后台发布中心</span>
    </footer>
</div>
</body>
</html>

front/templates/cms/category.html
{% extends 'cms/base.html' %}

{% block head %}
    <script src="{% static 'js/addcategory.min.js' %}"></script>
{% endblock %}
{% block content-header %}
    <h1>新闻分类</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <button class="btn btn-primary" id="add-btn">添加分类</button>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>新闻分类</th>
                            <th>新闻数量</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for category in categories %}
                            <tr data-pk="{{ category.pk }}" data-name="{{ category.name }}">
                                <td>{{ category.name }}</td>
                                <td>{{ category.news_set.count }}</td>
                                <td>
                                    <button class="btn btn-danger delete-btn btn-xs">删除</button>
                                    <button class="btn btn-primary edit-btn btn-xs">编辑</button>
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/cms/index.html
{% extends 'cms/base.html' %}


{% block content-header %}
{% endblock %}


{% block content %}
  这是cms首页
{% endblock %}

front/templates/cms/newsmanage.html
{% extends 'cms/base.html' %}

{% block head %}
    <link rel="stylesheet"
          href="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script src="{% static 'js/newsmanage.min.js' %}"></script>

{% endblock %}

{% block content-header %}
    <h1>新闻管理</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <form action="" class="form-inline">
                        <div class="form-group">
                            <label>时间：</label>
                            {% if start %}
                                <input type="text" class="form-control" placeholder="开始时间" id="starttime" name="start"
                                       readonly value="{{ start }}">
                            {% else %}
                                <input type="text" class="form-control" placeholder="开始时间" id="starttime" name="start"
                                       readonly>
                            {% endif %}

                            <span>==></span>
                            {% if end %}
                                <input type="text" class="form-control" placeholder="结束时间" id="endtime" name="end"
                                       readonly value="{{ end }}">
                            {% else %}
                                <input type="text" class="form-control" placeholder="结束时间" id="endtime" name="end"
                                       readonly>
                            {% endif %}
                        </div>
                        <div class="form-group" style="margin-left: 40px">
                            <label for="key-word">关键字查找:</label>
                            {% if title %}
                                <input type="text" class="form-control" id="key-word" placeholder="篮球" name="title"
                                       value="{{ title }}">
                            {% else %}
                                <input type="text" class="form-control" id="key-word" placeholder="篮球" name="title">
                            {% endif %}
                        </div>
                        <div class="form-group dropdown" style="margin-left: 40px">
                            <label for="category-input">按分类查找：</label>
                            <select name="category" id="category-input" class="form-control">
                                {% if category_id == 0 %}
                                    <option value="0" selected>全部分类</option>
                                {% else %}
                                    <option value="0">全部分类</option>
                                {% endif %}
                                {% for category in categories %}
                                    {% if category.id == category_id %}
                                        <option value="{{ category.id }}" selected>{{ category.name }}</option>
                                    {% else %}
                                        <option value="{{ category.id }}">{{ category.name }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group" style="margin-left: 50px">
                            <button class="btn btn-primary">查询</button>
                        </div>
                        <div class="form-group ">
                            <a href="{% url 'cms:news_manage' %}" class="btn btn-warning">清除查询</a>
                        </div>
                    </form>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th class="col-md-4">新闻标题</th>
                            <th class="col-md-2">新闻分类</th>
                            <th class="col-md-2">发布时间</th>
                            <th class="col-md-2">发布人</th>
                            <th class="col-md-2">操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for news in newses %}
                            <tr>
                                <td><a target="_blank"
                                       href="{% url 'news:news_detail' news_id=news.id %}">{{ news.title }}</a></td>
                                <td>{{ news.category.name }}</td>
                                <td>{{ news.pub_time }}</td>
                                <td>{{ news.author.username }}</td>
                                <td>
                                    <button class="btn btn-danger delete-btn btn-xs" data-news-id="{{ news.id }}">删除</button>
                                    <a href="{% url 'cms:edit_news' %}?news_id={{ news.id }}" class="btn btn-primary btn-xs" >编辑</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="footer"></div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/cms/staffs.html
{% extends 'cms/base.html' %}

{% block head %}
    <script src="{% static 'js/staffmanage.min.js' %}"></script>
    <script src="{% static 'js/addstaff.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>员工管理</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th class="col-md-3">员工姓名</th>
                            <th class="col-md-3">员工手机</th>
                            <th class="col-md-3">员工权限</th>
                            <th class="col-md-3">操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for staff in staffs %}
                            <tr>
                                <td>{{ staff.username }}</td>
                                <td>{{ staff.telephone }}</td>
                                <td>
                                    {% if staff.is_superuser %}
                                        <span>超级管理员</span>
                                    {% else %}
                                        {% for group in staff.groups.all %}
                                            {{ group.name }}
                                        {% endfor %}

                                    {% endif %}
                                </td>
                                <td>
                                    <button class="btn btn-danger delete-btn btn-xs"
                                            data-staff-telephone="{{ staff.telephone }}">删除
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
                {% if user.is_superuser %}
                    <div class="box-footer">
                        <h3>权限管理：</h3>
                        <form action="" method="post">

                            {% csrf_token %}
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="telephone-input">添加员工手机：</label>
                                    <input type="text" class="form-control" name="telephone" placeholder="员工手机号">
                                </div>
                                <div class="form-group dropdown">
                                    <label for="group-input">选择权限:</label>
                                    <select name="group" id="group-input" class="form-control">
                                        {% for group in groups %}
                                            <option value="{{ group.id }}">{{ group.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="box-footer">
                                <button class="btn btn-primary pull-right" id="add-group-btn">确认添加</button>
                            </div>
                        </form>
                    </div>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}