apps/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'

urlpatterns = [
    path('index/', views.index_cms, name='index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('category_news/', views.category_news, name='category_news'),
    path('add_category/', views.add_category, name='add_category'),
    path('edit_category/', views.edit_category, name='edit_category'),
    path('del_category/', views.del_category, name='del_category'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('news_manage/', views.NewsManage.as_view(), name='news_manage'),
    path('edit_news/', views.EditNewsView.as_view(), name='edit_news'),
    path('del_news/', views.del_news, name='del_news'),
    path('staff_manage/', views.StaffView.as_view(), name='staff_manage'),
    path('del_staff/', views.del_staff, name='del_staff'),
]

apps/login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha_view, name='img_captcha'),

]

apps/news/urls.py
from . import views
from django.urls import path

app_name = 'news'

urlpatterns = [
    path('news_list/', views.news_list, name='news_list'),
    path('<int:news_id>/', views.news_detail, name='news_detail'),
    path('basketball_news/', views.basket_news_view, name='basketball_news'),
    path('autocar_news/', views.autocar_news_view, name='autocar_news'),
    path('comment/', views.comment_view, name='comment'),
]

mysite/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.news import views

urlpatterns = [
    path('',views.index_view, name='index'),
    path('news/', include('apps.news.urls')),
    path('auth/', include('apps.login.urls')),
    path('cms/', include('apps.cms.urls')),
    path('ueditor/', include('apps.ueditor.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# 添加MEDIA_ROOT下的访问路径

front/templates/base/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/body.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.min.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/ajax.min.js' %}"></script>
    <script src="{% static 'js/alert.min.js' %}"></script>
    <link rel="shortcut icon" href="#"/>
    <title>{% block title %}
    {% endblock %}</title>
    {% block css %}{% endblock %}
</head>
<body>
<header class="header">
    <div class="container">
        <div class="logo-box">
            <a href="/">Boke</a>
        </div>
        <ul class="nav">
            <li><a href="/">Boke首页</a></li>
            <li><a href="/">个人博客</a></li>
            <li><a href="{% url 'news:basketball_news' %}">篮球新闻</a></li>
            <li><a href="{% url 'news:autocar_news' %}">汽车新闻</a></li>
        </ul>
        <div class="auth-box">
            {% if user.is_authenticated %}

                <a>{{ user.username }}</a> |
                {% if user.is_staff %}
                    <a href="{% url 'cms:index' %}">管理系统</a> |
                {% endif %}
                <a href="{% url 'login:logout' %}">退出登录</a>
            {% else %}
                <a href="{% url 'login:login' %}">登录</a> ||
                <a href="{% url 'login:register' %}">注册</a>
            {% endif %}

        </div>
    </div>
</header>

{% block main %}{% endblock %}

</body>
</html>